import assert from 'node:assert/strict';
import {createCameraSession,CAMERA_STATES,classifyCameraError} from '../src/camera.js';
let stopped=0,revoked=[],created=0,drawn=[],requested=[];
const track={stop(){stopped++;},getCapabilities(){return {torch:true};},async applyConstraints(){}};
const stream={getTracks(){return [track];},getVideoTracks(){return [track];}};
const mediaDevices={async getUserMedia(constraints){requested.push(constraints);return stream;}};
const urlApi={createObjectURL(blob){created++;return `blob:mock-${created}`;},revokeObjectURL(url){revoked.push(url);}};
const canvasFactory=()=>({width:0,height:0,getContext(){return {drawImage(...args){drawn.push(args);}};},toBlob(cb,type,quality){assert.equal(type,'image/jpeg');assert.equal(quality,.94);cb(new Blob(['full-resolution-frame'],{type}));}});
const session=createCameraSession({mediaDevices,urlApi,secureContext:true,canvasFactory});
const video={videoWidth:4032,videoHeight:3024,srcObject:null,async play(){this.played=true;},pause(){this.paused=true;},setAttribute(){}};
let r=await session.open(video);assert.equal(r.ok,true);assert.equal(session.getState(),CAMERA_STATES.LIVE);assert.equal(requested[0].video.facingMode.ideal,'environment');assert.equal(requested[0].video.width.ideal,1920);
await session.open(video);assert.equal(requested.length,1,'same live stream is reused');
const shot=await session.capture(video);assert.equal(shot.width,4032);assert.equal(shot.height,3024);assert.equal(shot.source,'camera');assert.equal(shot.blob.type,'image/jpeg');assert.equal(session.getState(),CAMERA_STATES.REVIEW);assert.equal(stopped,1,'capture stops camera tracks');assert.equal(video.srcObject,null);assert.equal(drawn[0][3],4032);assert.equal(drawn[0][4],3024);
const confirmed=session.confirmImage();assert.equal(session.getState(),CAMERA_STATES.CONFIRMED);assert.equal(session.getConfirmedImage().blob,shot.blob,'confirmed OCR input reuses the captured Blob');assert.equal(confirmed.url,shot.url);
session.clearConfirmedImage();assert.equal(session.getConfirmedImage(),null);assert.deepEqual(revoked,['blob:mock-1']);
const permissionSession=createCameraSession({mediaDevices:{async getUserMedia(){const e=new Error('denied');e.name='NotAllowedError';throw e;}},urlApi,secureContext:true});const denied=await permissionSession.open({...video,srcObject:null});assert.equal(denied.kind,'permission');assert.equal(permissionSession.getState(),CAMERA_STATES.ERROR);
assert.equal(classifyCameraError(new Error('https required'),{secureContext:false}).kind,'insecure');
let tries=0;const fallbackSession=createCameraSession({mediaDevices:{async getUserMedia(c){tries++;if(tries===1){const e=new Error('constraint');e.name='OverconstrainedError';throw e;}assert.equal(c.video,true);return stream;}},urlApi,secureContext:true});assert.equal((await fallbackSession.open({...video,srcObject:null})).ok,true);assert.equal(tries,2,'unsupported constraints retry with device defaults');fallbackSession.stop();assert.ok(stopped>=2);
let resolvePending;let calls=0;const pendingSession=createCameraSession({mediaDevices:{getUserMedia(){calls++;return new Promise(resolve=>resolvePending=resolve);}},urlApi,secureContext:true});const p1=pendingSession.open({...video,srcObject:null});const p2=pendingSession.open({...video,srcObject:null});assert.equal(calls,1,'parallel starts do not open duplicate streams');pendingSession.stop();resolvePending(stream);await p1;await p2;assert.ok(stopped>=3,'late stream is stopped after screen was exited');
let galleryRevoked=[];const gallerySession=createCameraSession({mediaDevices,urlApi:{createObjectURL(){return 'blob:gallery';},revokeObjectURL(url){galleryRevoked.push(url);}},secureContext:true});const photo=new Blob(['gallery-photo'],{type:'image/jpeg'});const preview=await gallerySession.selectImage(photo);assert.equal(preview.blob,photo);assert.equal(preview.source,'gallery');gallerySession.confirmImage();assert.equal(gallerySession.getConfirmedImage().blob,photo);gallerySession.clearConfirmedImage();assert.deepEqual(galleryRevoked,['blob:gallery']);
const appSource=await (await import('node:fs/promises')).readFile(new URL('../src/app.js',import.meta.url),'utf8');
assert.ok(appSource.includes('accept="image/*"'));assert.ok(!appSource.includes('capture="environment"'));
const cameraSource=await (await import('node:fs/promises')).readFile(new URL('../src/camera.js',import.meta.url),'utf8');assert.doesNotMatch(cameraSource,/tesseract|recognizeText|ocr\(/i);
console.log('PASS cámara mock: permiso/errores, constraint trasera, fallback, evita streams duplicados, captura completa, tracks detenidos, selección galería, Blob confirmado y URL liberada.');
