import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {makeWifiPayload,validateNetwork,escapeWifi} from '../src/utils.js';
const special=makeWifiPayload({ssid:'Casa, sala; "5G"',password:'p;ass\\word,:"',security:'WPA/WPA2'});
assert.equal(special,'WIFI:T:WPA;S:Casa\\, sala\\; \\"5G\\";P:p\\;ass\\\\word\\,\\:\\";;');
assert.equal(makeWifiPayload({ssid:'Libre',security:'Sin contraseña'}),'WIFI:T:nopass;S:Libre;;');
assert.equal(makeWifiPayload({ssid:'WEP net',password:'abcde',security:'WEP'}),'WIFI:T:WEP;S:WEP net;P:abcde;;');
assert.equal(makeWifiPayload({ssid:'WPA3 net',password:'abcdefgh',security:'WPA3'}),'WIFI:T:WPA;S:WPA3 net;P:abcdefgh;;');
assert.equal(makeWifiPayload({ssid:'Escondida',password:'abcdefgh',hidden:true}),'WIFI:T:WPA;S:Escondida;P:abcdefgh;H:true;;');
assert.equal(validateNetwork({ssid:'Casa',password:'12345678',security:'WPA/WPA2'}),'');
assert.equal(validateNetwork({ssid:'Libre',password:'',security:'Sin contraseña'}),'');
assert.match(validateNetwork({ssid:'Casa',password:'123',security:'WPA/WPA2'}),/8–63/);
assert.match(validateNetwork({ssid:'',password:'abcdefgh',security:'WPA/WPA2'}),/SSID/);
assert.equal(validateNetwork({ssid:'Wep',password:'abcde',security:'WEP'}),'');
assert.equal(escapeWifi('a:b,c;d"e\\f'),'a\\:b\\,c\\;d\\"e\\\\f');
const vendor=fs.readFileSync(new URL('../vendor/qrcode-generator.js',import.meta.url),'utf8');
const context={console};vm.createContext(context);vm.runInContext(vendor,context);
assert.equal(typeof context.qrcode,'function','QR encoder global is exposed');
const qr=context.qrcode(0,'M');qr.addData(special,'Byte');qr.make();
const svg=qr.createSvgTag(6,4,'Wi-Fi QR','Casa');
assert.match(svg,/<svg/);assert.match(svg,/<path/);assert.ok(qr.getModuleCount()>20);
for(const f of ['index.html','manifest.webmanifest','service-worker.js','src/app.js','src/config.js','src/validation.js','src/lab-diagnostics.js','src/camera.js','src/router-parser.js','src/operator-detector.js','src/operator-profiles/index.js','src/operator-profiles/digi.js','src/storage.js','src/qr.js','src/share.js','src/router.js'])assert.ok(fs.existsSync(new URL(`../${f}`,import.meta.url)),`${f} exists`);
const manifest=JSON.parse(fs.readFileSync(new URL('../manifest.webmanifest',import.meta.url),'utf8'));
assert.equal(manifest.name,'Netlixy');assert.equal(manifest.short_name,'Netlixy');assert.equal(manifest.start_url,'./');assert.equal(manifest.scope,'./');assert.equal(manifest.display,'standalone');assert.ok(manifest.icons.some(icon=>icon.sizes==='192x192'));
const app=fs.readFileSync(new URL('../src/app.js',import.meta.url),'utf8');assert.match(app,/data-action="copy-data"/);assert.match(app,/copyTextToClipboard\(details\)/);assert.match(app,/Datos copiados\./);const sw=fs.readFileSync(new URL('../service-worker.js',import.meta.url),'utf8');
assert.ok(fs.existsSync(new URL('../css/theme.css',import.meta.url)),'restyling theme stylesheet exists');const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
assert.match(html,/<title>Netlixy<\/title>/);assert.doesNotMatch(html,/(?:href|src)="\//,'GitHub Pages resources remain relative to the project path');
assert.match(sw,/const CACHE_NAME='netlixy-v1\.11\.3'/);assert.match(sw,/key\.startsWith\('wifi-connect-'\)\|\|key\.startsWith\('netlixy-'\)/,'activation removes app caches only');
assert.match(fs.readFileSync(new URL('../src/app.js',import.meta.url),'utf8'),/register\('\.\/service-worker\.js',\{scope:'\.\/'\}\)/);
for(const path of ['./','./css/theme.css','./vendor/qrcode-generator.js','./src/app.js','./src/config.js','./src/validation.js','./src/lab-diagnostics.js','./src/router-parser.js','./src/operator-detector.js','./src/operator-profiles/index.js','./src/operator-profiles/digi.js','./src/operator-profiles/movistar-o2.js','./src/operator-profiles/orange-jazztel.js','./src/operator-profiles/vodafone-lowi.js','./src/camera.js'])assert.ok(sw.includes(path),`service worker precaches ${path}`);
for(const path of ['./vendor/tesseract/core/worker.min.js','./vendor/tesseract/core/tesseract-core-lstm.wasm.js','./vendor/tesseract/core/tesseract-core-lstm.wasm','./vendor/tesseract/core/tesseract-core-simd-lstm.wasm','./vendor/tesseract/core/tesseract-core-relaxedsimd-lstm.wasm','./vendor/tesseract/lang/eng.traineddata.gz','./vendor/tesseract/lang/spa.traineddata.gz']){assert.ok(sw.includes(path),`service worker has lazy OCR resource ${path}`);assert.ok(fs.existsSync(new URL(`../${path.slice(2)}`,import.meta.url)),`local OCR resource exists ${path}`);}
assert.ok(!sw.slice(sw.indexOf('const APP_SHELL'),sw.indexOf('];',sw.indexOf('const APP_SHELL'))).includes('traineddata'),'OCR language files are lazy, not startup precache');
console.log('PASS: payload WPA/WPA3/WEP/red abierta/red oculta, escapes, validación SSID/contraseña, encoder QR produce SVG, manifest y shell offline presentes.');
