import assert from 'node:assert/strict';
import {analyzeRouterImage} from '../src/router-image-analysis.js';
import {buildScanPlan} from '../src/scan-flow.js';
const input=new Blob(['x'],{type:'image/jpeg'}),calls=[];let qrPassed;
const catalanDiagnosticText='VeraDemo_B96AB4\nContrasenya WPA\nPrivateDemoPass987';const catalanDiagnostic=await analyzeRouterImage(input,{decodeQr:async()=>({status:'not-found'}),recognize:async()=>({rawText:catalanDiagnosticText,normalizedText:catalanDiagnosticText,confidence:90,passes:[{id:'color',normalizedText:catalanDiagnosticText,confidence:90}]})});assert.ok(catalanDiagnostic.diagnostics.ocrPasses[0].passwordLabelDetected,'Catalan password label is represented in safe scan diagnostics');assert.ok(catalanDiagnostic.diagnostics.parser.ssidReasons.some(reason=>reason.includes('etiqueta de contraseña')));assert.ok(catalanDiagnostic.diagnostics.parser.passwordReasons.some(reason=>reason.includes('catalana')));assert.equal(JSON.stringify(catalanDiagnostic.diagnostics).includes('PrivateDemoPass987'),false,'persistent scan diagnostics retain parser failure/evidence reasons without Wi-Fi credentials');
const result=await analyzeRouterImage(input,{decodeQr:async()=>{calls.push('qr');return {type:'wifi',status:'wifi',ssid:'ExampleNet',password:'ExamplePass123',security:'WPA/WPA2'};},recognize:async(_blob,options)=>{calls.push('ocr');qrPassed=options.qrResult;return {rawText:'RED Wi-Fi ExampleNet',normalizedText:'RED Wi-Fi ExampleNet',confidence:90,passes:[]};}});
assert.deepEqual(calls,['qr','ocr']);assert.equal(qrPassed.status,'wifi');assert.equal(result.parsed.ssid.value,'ExampleNet');assert.equal(result.source,'qr');
const fallback=await analyzeRouterImage(input,{decodeQr:async()=>({type:'wifi',status:'wifi',ssid:'QRNet',password:'QRPass1234',security:'WPA/WPA2'}),recognize:async()=>{throw Error('OCR failed');}});assert.equal(fallback.parsed.ssid.value,'QRNet');assert.match(fallback.ocrError,/OCR failed/);
const partial=await analyzeRouterImage(input,{decodeQr:async()=>({type:'wifi',status:'wifi',source:'jsQR',ssid:'ExampleNet',password:'PrivatePass123',security:'WPA/WPA2'}),recognize:async()=>({rawText:'RED Wi-Fi: ExampleNet serial barcode noise',normalizedText:'RED Wi-Fi: ExampleNet serial barcode noise',confidence:91,passes:[{id:'color',rawText:'RED Wi-Fi: ExampleNet serial barcode noise',normalizedText:'RED Wi-Fi: ExampleNet serial barcode noise',confidence:91,durationMs:2}]})});assert.equal(partial.parsed.ssid.value,'ExampleNet');assert.equal(partial.parsed.password.value,'PrivatePass123');assert.equal(partial.parsed.password.source,'qr');assert.equal(partial.parsed.warnings.some(item=>item.includes('no coinciden')),false,'OCR label continuation is partial corroboration, not a credential conflict');assert.equal(buildScanPlan(partial.parsed).state,'ready','valid QR credentials remain usable when OCR has no password');assert.equal(partial.diagnostics.ocrPasses[0].ssidLabelDetected,true);assert.equal(partial.diagnostics.ocrPasses[0].passwordLabelDetected,false);assert.equal(partial.diagnostics.ocrPasses[0].passwordDetected,false);assert.equal(partial.diagnostics.fusion.passwordDetected,true);assert.equal(partial.diagnostics.fusion.passwordSource,'QR');assert.equal(JSON.stringify(partial.diagnostics).includes('PrivatePass123'),false,'diagnostics never retain credentials');
const noisy=await analyzeRouterImage(input,{decodeQr:async()=>({type:'wifi',status:'wifi',ssid:'ExampleNet',password:'PrivatePass123',security:'WPA/WPA2'}),recognize:async()=>({rawText:'RED Wi-Fi: ExampleNet\nCLAVE Wi-Fi: Oth3rS3cret',normalizedText:'RED Wi-Fi: ExampleNet\nCLAVE Wi-Fi: Oth3rS3cret',confidence:91,passes:[{id:'color',normalizedText:'RED Wi-Fi: ExampleNet\nCLAVE Wi-Fi: Oth3rS3cret',confidence:91}]})});assert.equal(buildScanPlan(noisy.parsed).state,'ready','one OCR password mismatch must not invalidate an independently valid Wi-Fi QR');assert.equal(noisy.parsed.password.value,'PrivatePass123');assert.equal(noisy.parsed.password.source,'qr');
const noisySsid=await analyzeRouterImage(input,{decodeQr:async()=>({type:'wifi',status:'wifi',ssid:'ExampleNet',password:'PrivatePass123',security:'WPA/WPA2'}),recognize:async()=>({rawText:'RED Wi-Fi: ExampleNet 1 serial barcode noise',normalizedText:'RED Wi-Fi: ExampleNet 1 serial barcode noise',confidence:91,passes:[{id:'color',normalizedText:'RED Wi-Fi: ExampleNet 1 serial barcode noise',confidence:91}]})});assert.equal(buildScanPlan(noisySsid.parsed).state,'ready','an exact QR SSID followed by OCR noise stays usable');assert.equal(noisySsid.parsed.password.value,'PrivatePass123');
const conflictText='RED Wi-Fi: AnotherNet\nCLAVE Wi-Fi: OtherSecret987';const conflict=await analyzeRouterImage(input,{decodeQr:async()=>({type:'wifi',status:'wifi',ssid:'ExampleNet',password:'PrivatePass123',security:'WPA/WPA2'}),recognize:async()=>({rawText:conflictText,normalizedText:conflictText,confidence:91,passes:[{id:'color',normalizedText:conflictText,confidence:91},{id:'grayscale-contrast',normalizedText:conflictText,confidence:89}]})});assert.equal(buildScanPlan(conflict.parsed).state,'review','a repeated strong QR/OCR disagreement must require review');assert.deepEqual(buildScanPlan(conflict.parsed).fields,['ssid','password']);assert.equal(conflict.parsed.passwordCandidates.length,2,'preserve both conflicting password candidates');
const diagnosticEvents=[];const diagnosticRun=await analyzeRouterImage(input,{decodeQr:async()=>({type:'wifi',status:'wifi',ssid:'SafeName',password:'HiddenCredential987',security:'WPA/WPA2',source:'jsQR',attempts:[{width:800,height:600,durationMs:12,found:true}]}),recognize:async()=>{throw new Error('OCR failure');},onDiagnostics:event=>diagnosticEvents.push(event)});assert.equal(diagnosticRun.parsed.password.value,'HiddenCredential987');assert.ok(diagnosticEvents.some(item=>item.stage==='qr-complete'&&item.qrHasPassword),'QR diagnostics are emitted before OCR');assert.ok(diagnosticEvents.some(item=>item.stage==='ocr-failed'&&item.finalPasswordAvailable),'QR result survives a later OCR exception');assert.equal(JSON.stringify(diagnosticEvents).includes('HiddenCredential987'),false,'incremental diagnostics never include credentials');assert.equal(diagnosticRun.diagnostics.qr.attempts[0].width,800);
await assert.rejects(()=>analyzeRouterImage(new Blob(['x'],{type:'text/plain'})),/fotografía válida/);
console.log('router-image-analysis: QR-first, shared OCR/parser and local fallback passed');



