import assert from 'node:assert/strict';
import {analyzeRouterImage} from '../src/router-image-analysis.js';
import {buildScanPlan} from '../src/scan-flow.js';
const input=new Blob(['x'],{type:'image/jpeg'}),calls=[];let qrPassed;
const result=await analyzeRouterImage(input,{decodeQr:async()=>{calls.push('qr');return {type:'wifi',status:'wifi',ssid:'ExampleNet',password:'ExamplePass123',security:'WPA/WPA2'};},recognize:async(_blob,options)=>{calls.push('ocr');qrPassed=options.qrResult;return {rawText:'RED Wi-Fi ExampleNet',normalizedText:'RED Wi-Fi ExampleNet',confidence:90,passes:[]};}});
assert.deepEqual(calls,['qr','ocr']);assert.equal(qrPassed.status,'wifi');assert.equal(result.parsed.ssid.value,'ExampleNet');assert.equal(result.source,'qr');
const fallback=await analyzeRouterImage(input,{decodeQr:async()=>({type:'wifi',status:'wifi',ssid:'QRNet',password:'QRPass1234',security:'WPA/WPA2'}),recognize:async()=>{throw Error('OCR failed');}});assert.equal(fallback.parsed.ssid.value,'QRNet');assert.match(fallback.ocrError,/OCR failed/);
const partial=await analyzeRouterImage(input,{decodeQr:async()=>({type:'wifi',status:'wifi',source:'jsQR',ssid:'ExampleNet',password:'PrivatePass123',security:'WPA/WPA2'}),recognize:async()=>({rawText:'RED Wi-Fi: ExampleNet serial barcode noise',normalizedText:'RED Wi-Fi: ExampleNet serial barcode noise',confidence:91,passes:[{id:'color',rawText:'RED Wi-Fi: ExampleNet serial barcode noise',normalizedText:'RED Wi-Fi: ExampleNet serial barcode noise',confidence:91,durationMs:2}]})});assert.equal(partial.parsed.ssid.value,'ExampleNet');assert.equal(partial.parsed.password.value,'PrivatePass123');assert.equal(partial.parsed.password.source,'qr');assert.equal(partial.parsed.warnings.some(item=>item.includes('no coinciden')),false,'OCR label continuation is partial corroboration, not a credential conflict');assert.equal(buildScanPlan(partial.parsed).state,'ready','valid QR credentials remain usable when OCR has no password');assert.equal(partial.diagnostics.ocrPasses[0].ssidLabelDetected,true);assert.equal(partial.diagnostics.ocrPasses[0].passwordLabelDetected,false);assert.equal(partial.diagnostics.ocrPasses[0].passwordDetected,false);assert.equal(partial.diagnostics.fusion.passwordDetected,true);assert.equal(partial.diagnostics.fusion.passwordSource,'QR');assert.equal(JSON.stringify(partial.diagnostics).includes('PrivatePass123'),false,'diagnostics never retain credentials');
const conflict=await analyzeRouterImage(input,{decodeQr:async()=>({type:'wifi',status:'wifi',ssid:'ExampleNet',password:'PrivatePass123',security:'WPA/WPA2'}),recognize:async()=>({rawText:'RED Wi-Fi: ExampleNet\nCLAVE Wi-Fi: OtherSecret987',normalizedText:'RED Wi-Fi: ExampleNet\nCLAVE Wi-Fi: OtherSecret987',confidence:91,passes:[]})});assert.equal(buildScanPlan(conflict.parsed).state,'review','a real QR/OCR password conflict must require review');assert.equal(conflict.parsed.passwordCandidates.length,2,'preserve both conflicting password candidates');
await assert.rejects(()=>analyzeRouterImage(new Blob(['x'],{type:'text/plain'})),/fotografía válida/);
console.log('router-image-analysis: QR-first, shared OCR/parser and local fallback passed');



