import assert from 'node:assert/strict';
import {createOcrService,normalizeOcrText,OCR_LANGUAGES} from '../src/ocr.js';
import {prepareImageForOcr,MAX_OCR_DIMENSION} from '../src/image-processing.js';
import {parseRouterLabel} from '../src/router-parser.js';

assert.equal(normalizeOcrText('  WiFi  \r\nSSID:   Café_5G\rPassword:\t  abc123  '),'WiFi\nSSID: Café_5G\nPassword: abc123');
assert.equal(normalizeOcrText('O I S 0 1 5'),'O I S 0 1 5','normalization must not guess characters');
assert.equal(OCR_LANGUAGES,'spa+eng');
await assert.rejects(()=>prepareImageForOcr(new Blob(['x'],{type:'text/plain'})),/fotografía válida/);
await assert.rejects(()=>prepareImageForOcr(new Blob([],{type:'image/png'})),/vacía/);

const oldBitmap=globalThis.createImageBitmap;let decodedOptions,drawDims=[],released=0,canvasDims=[];
globalThis.createImageBitmap=async(_blob,options)=>{decodedOptions=options;return {width:4000,height:2000,close(){released++;}};};
const fakeCanvas=()=>({width:0,height:0,getContext(){return {drawImage(_image,_x,_y,width,height){drawDims.push([width,height]);}};},toBlob(callback,type,quality){canvasDims.push([this.width,this.height,type,quality]);callback(new Blob(['jpeg'],{type}));}});
const prepared=await prepareImageForOcr(new Blob(['large-photo'],{type:'image/jpeg'}),{canvasFactory:fakeCanvas,urlApi:{createObjectURL(){throw Error('not needed');},revokeObjectURL(){}}});
if(oldBitmap===undefined)delete globalThis.createImageBitmap;else globalThis.createImageBitmap=oldBitmap;
assert.deepEqual(decodedOptions,{imageOrientation:'from-image'});assert.equal(prepared.width,MAX_OCR_DIMENSION);assert.equal(prepared.height,1400);assert.equal(prepared.wasResized,true);assert.equal(prepared.orientationNormalized,true);assert.equal(released,1);assert.deepEqual(drawDims,[[2800,1400],[1200,600]]);assert.equal(canvasDims[0][3],.96);assert.equal(canvasDims[1][2],'image/jpeg');

let grayPixels;globalThis.createImageBitmap=async()=>({width:400,height:200,close(){}});const grayPrepared=await prepareImageForOcr(new Blob(['photo'],{type:'image/jpeg'}),{variant:'grayscale',canvasFactory:()=>({width:0,height:0,getContext(){return {drawImage(){},getImageData(){return {data:new Uint8ClampedArray([100,120,140,255])};},putImageData(image){grayPixels=[...image.data];}};},toBlob(callback,type){callback(new Blob(['gray'],{type}));}}),urlApi:{createObjectURL(){throw Error('not needed');},revokeObjectURL(){}}});if(oldBitmap===undefined)delete globalThis.createImageBitmap;else globalThis.createImageBitmap=oldBitmap;assert.equal(grayPixels[0],grayPixels[1]);assert.equal(grayPixels[1],grayPixels[2],'alternate image is genuinely grayscale with moderate contrast');assert.ok(grayPixels[0]>0&&grayPixels[0]<255);assert.equal(grayPrepared.width,600);assert.equal(grayPrepared.height,300,'alternate preprocessing moderately upscales small labels within the 2800 px limit');

const stages=[],progress=[];let termination=0,recognitionInput,workerConfig;
const fakeWorker={async recognize(image){recognitionInput=image;return {data:{text:'  SSID: TEST_WIFI\r\nWLAN Key: A1B2  ',confidence:81.25}};},async terminate(){termination++;}};
const service=createOcrService({paths:()=>({workerPath:'/local/worker.js',corePath:'/local/core/',langPath:'/local/lang'}),preprocess:async(blob,{onStage})=>{onStage('Imagen preparada');return {blob:new Blob(['processed'],{type:'image/jpeg'}),previewBlob:new Blob(['preview'],{type:'image/jpeg'}),sourceWidth:3000,sourceHeight:2000,width:2800,height:1867,wasResized:true};},loadEngine:async()=>({OEM:{LSTM_ONLY:1},PSM:{AUTO:'3'},createWorker:async(langs,oem,options,config)=>{assert.equal(langs,'spa+eng');assert.equal(oem,1);assert.equal(options.workerBlobURL,false);assert.equal(options.gzip,true);workerConfig=config;options.logger({status:'recognizing text',progress:.6});return fakeWorker;}})});
const result=await service(new Blob(['original'],{type:'image/jpeg'}),{onStage:stage=>stages.push(stage),onProgress:value=>progress.push(value)});
assert.equal(result.rawText,'[OCR color]\n  SSID: TEST_WIFI\r\nWLAN Key: A1B2  \n\n[OCR grayscale-contrast]\n  SSID: TEST_WIFI\r\nWLAN Key: A1B2  ');assert.match(result.normalizedText,/SSID: TEST_WIFI\nWLAN Key: A1B2/);assert.equal(result.confidence,81.3);assert.equal(result.passes.length,2,'OCR sourced credentials require an independent alternate pass even when global confidence is high');assert.deepEqual(result.passes.map(pass=>pass.id),['color','grayscale-contrast']);assert.ok(result.durationMs>=0);assert.equal(result.image.processedWidth,2800);assert.equal(result.processedPreviewBlob.type,'image/jpeg');assert.equal(recognitionInput.type,'image/jpeg');assert.equal(workerConfig.tessedit_pageseg_mode,'3');assert.equal(termination,1);assert.ok(stages.includes('Preparando imagen'));assert.ok(stages.includes('Mejorando lectura'));assert.deepEqual(progress,[{status:'Detectando texto',progress:.6}]);
let missingPasswordPass=0;const passwordFallback=createOcrService({paths:()=>({}),preprocess:async(_blob,{variant})=>({blob:new Blob([variant],{type:'image/jpeg'}),previewBlob:new Blob(['preview'],{type:'image/jpeg'}),sourceWidth:800,sourceHeight:600,width:800,height:600}),loadEngine:async()=>({createWorker:async()=>({async recognize(){missingPasswordPass++;return {data:{text:missingPasswordPass===1?'RED Wi-Fi: Livebox6-DFD9':'RED Wi-Fi: Livebox6-DFD9\nCLAVE Wi-Fi: TestSecret123',confidence:94}};},async terminate(){}})})});const fallbackOcr=await passwordFallback(new Blob(['camera'],{type:'image/jpeg'}),{qrResult:{status:'wifi',ssid:'Livebox6-DFD9',password:'QrSecret123',security:'WPA/WPA2'}});assert.equal(missingPasswordPass,2,'missing OCR password always triggers grayscale even with high confidence and a matching QR');assert.deepEqual(fallbackOcr.passes.map(pass=>pass.id),['color','grayscale-contrast']);
let conflictPass=0;const conflictFallback=createOcrService({paths:()=>({}),preprocess:async(_blob,{variant})=>({blob:new Blob([variant],{type:'image/jpeg'}),previewBlob:new Blob(['preview'],{type:'image/jpeg'}),sourceWidth:800,sourceHeight:600,width:800,height:600}),loadEngine:async()=>({createWorker:async()=>({async recognize(){conflictPass++;return {data:{text:conflictPass===1?'RED Wi-Fi: Livebox6-DFD9\nCLAVE Wi-Fi: WrongPass987':'RED Wi-Fi: Livebox6-DFD9\nCLAVE Wi-Fi: WrongPass987',confidence:96}};},async terminate(){}})})});await conflictFallback(new Blob(['camera'],{type:'image/jpeg'}),{qrResult:{status:'wifi',ssid:'Livebox6-DFD9',password:'QrSecret123',security:'WPA/WPA2'}});assert.equal(conflictPass,2,'a high-confidence OCR password that conflicts with QR also triggers the alternate pass');
await assert.rejects(()=>service(null),/fotografía válida/);

const passVariants=[],recognitionSequence=[{data:{text:'| | SSID1: HUAWEI-2 4G-28bi 1\nSSID2: HUAWEI-5G-28bi\n| WLAN Key: dab918ck',confidence:80}},{data:{text:'IP:192 168 100 1\n1semame roo t\npassword: adminHWw a\nSSID1: HUAWEI-2 4G-28bi -—',confidence:63}}];let recognitionCount=0;
const multipass=createOcrService({paths:()=>({}),preprocess:async(_blob,options)=>{passVariants.push(options.variant);return {blob:new Blob([options.variant]),previewBlob:new Blob(['preview'],{type:'image/jpeg'}),sourceWidth:960,sourceHeight:1280,width:960,height:1280};},loadEngine:async()=>({createWorker:async()=>({async recognize(){return recognitionSequence[recognitionCount++];},async terminate(){}})})});
const fused=await multipass(new Blob(['photo'],{type:'image/jpeg'}));assert.deepEqual(passVariants,['color','grayscale']);assert.equal(fused.passes.length,2);assert.match(fused.normalizedText,/SSID1: HUAWEI-2 4G-28bi -—/);assert.match(fused.normalizedText,/SSID2: HUAWEI-5G-28bi/);assert.equal(fused.passes[1].confidence,63);assert.equal(recognitionCount,2);const fusedParsed=parseRouterLabel(fused);assert.equal(fusedParsed.password.value,'dab918ck');assert.ok(fusedParsed.excludedCandidates.some(candidate=>candidate.value==='adminHWw a'));assert.ok(fusedParsed.ssidCandidates.filter(candidate=>candidate.needsReview).length>=2);assert.ok(fusedParsed.password.sourcePasses.some(source=>source.pass==='color'));

let rejectRecognition,terminatedOnCancel=0;
const cancelService=createOcrService({paths:()=>({}),preprocess:async()=>({blob:new Blob(['x'],{type:'image/jpeg'}),previewBlob:new Blob(['p'],{type:'image/jpeg'})}),loadEngine:async()=>({createWorker:async()=>({recognize:()=>new Promise((_resolve,reject)=>rejectRecognition=reject),async terminate(){terminatedOnCancel++;rejectRecognition?.(new Error('worker terminated'));}})})});
const controller=new AbortController();const pending=cancelService(new Blob(['img'],{type:'image/jpeg'}),{signal:controller.signal});await new Promise(resolve=>setTimeout(resolve,0));controller.abort();await assert.rejects(pending,{name:'AbortError'});assert.equal(terminatedOnCancel,1);
console.log('PASS OCR wrapper/preproceso mock: validación, NFC/saltos/espacios sin sustituciones, orientación EXIF, límite 2800 px, vista comparativa, progreso, resultado estructurado, cancelación y terminate().');
