import assert from 'node:assert/strict';
import fs from 'node:fs';
import {buildScanPlan,createScannedNetwork,persistRecentBeforeReady} from '../src/scan-flow.js';
import {analyzeRouterImage} from '../src/router-image-analysis.js';

const orange={ssid:{value:'Livebox6-DFD9'},ssidCandidates:[{value:'Livebox6-DFD9',score:100,qrAgreement:true}],password:{value:'ValidSecret123'},security:{value:'WPA/WPA2'},qrAgreement:true};
assert.equal(buildScanPlan(orange).state,'ready','OCR/QR-confirmed single network goes straight to Red lista');
const qrOnlyPassword={...orange,password:{value:'QRCodeSecret123',source:'qr'},qrConflicts:{ssid:false,password:false,security:false}};const qrPlan=buildScanPlan(qrOnlyPassword);assert.equal(qrPlan.state,'ready','QR password remains ready with incomplete OCR');const readyNetwork=createScannedNetwork(qrOnlyPassword,qrPlan.candidate,{hidden:false});assert.equal(readyNetwork.password,'QRCodeSecret123','Red lista state receives the independently decoded QR password');assert.equal(readyNetwork.ssid,'Livebox6-DFD9');
const band24={value:'HUAWEI-2 4G-28bi -—',proposedValue:'HUAWEI-2.4G-28bi',band:'2.4 GHz',score:84,corrected:true,correctionConfidence:'high',correctionScore:8,needsReview:true};
const band5={value:'HUAWEI-5G-28bi',band:'5 GHz',score:82};
const huawei={ssid:{value:band5.value},ssidCandidates:[band24,band5],password:{value:'WlanSecret123'},security:{value:'WPA/WPA2'}};
const choose=buildScanPlan(huawei);assert.equal(choose.state,'choose-band');assert.deepEqual(choose.choices.map(item=>item.band),['2.4 GHz','5 GHz']);
assert.equal(buildScanPlan(huawei,{selectedCandidate:band24}).state,'ready','high-confidence contextual 2.4 GHz proposal does not force a full review');
assert.equal(buildScanPlan(huawei,{selectedCandidate:band5}).state,'ready');
const taggedHuawei={...huawei,ssidCandidates:[{...band5,score:100,reason:'Etiqueta SSID: valor en la misma línea',needsReview:true}],password:{value:'dab918ck',score:100,reason:'Etiqueta de contraseña Wi-Fi: valor en la misma línea',needsReview:true}};
assert.equal(buildScanPlan(taggedHuawei).state,'ready','strong labeled OCR candidates are usable despite a modest page-wide OCR confidence');
const conflict={...orange,qrConflicts:{ssid:false,password:true}};
assert.deepEqual(buildScanPlan(conflict).fields,['password'],'only the reliably conflicting field requires review');
const doubtful={...orange,ssidCandidates:[{value:'Livebox6-DFD9',score:100,needsReview:true}]};assert.deepEqual(buildScanPlan(doubtful).fields,['ssid'],'only the uncertain field is requested');
const missing={ssidCandidates:[],password:null};assert.equal(buildScanPlan(missing).state,'error','total failure uses the simple recovery screen');
const order=[];const recent=await persistRecentBeforeReady({ssid:'Casa'},{saveRecent:async network=>{order.push('saved');return {...network,type:'recent'};},showReady:async network=>{assert.equal(network.type,'recent');order.push('ready');}});assert.deepEqual(order,['saved','ready']);assert.equal(recent.type,'recent');
const app=fs.readFileSync(new URL('../src/app.js',import.meta.url),'utf8');
assert.match(app,/if\(action==='capture'\)[\s\S]*?camera\.confirmImage\(\);await beginOcr\(\)/,'a camera capture proceeds directly to analysis');
assert.match(app,/onDiagnostics:snapshot=>persistScanDiagnostics/,'safe diagnostics persist as the real analyzer advances, including before errors');assert.match(app,/data-action="validation-scan-copy"/,'validation mode exposes safe scan diagnostics copy');assert.match(app,/createScannedNetwork\(analysis\.parsed,candidate,analysis\.qr\)/,'Red lista uses the parsed QR password in the actual network state');
assert.match(app,/function promoteScannedNetwork\(\)[\s\S]*?toast\('Red guardada'\);await render\(\)/,'Guardar promotes the existing recent in place with a toast');
assert.match(app,/if\(action==='copy-password'\)[\s\S]*?touchRecentNetwork\(current\.id\)[\s\S]*?copyTextToClipboard\(current\.password\)/,'copying a recent password renews it and copies directly');
assert.match(app,/if\(action==='regenerate'\)[\s\S]*?qrReturnRoute='detail';route='qr'/,'Show QR remembers Red lista as its return destination');
assert.match(app,/if\(action==='back-qr'\)\{route=qrReturnRoute==='detail'\?'detail':'home'/,'QR returns directly to Red lista');
assert.match(app,/function bandChoiceScreen\(\)[\s\S]*?<h1>Elige la red<\/h1>[\s\S]*?data-scan-choice/,'two bands show a simple choice screen');
assert.match(app,/function ocrErrorScreen\(\)[\s\S]*?No he podido leer la etiqueta[\s\S]*?Repetir foto[\s\S]*?Elegir otra foto[\s\S]*?Introducir manualmente/,'total failure has exactly the three simple recovery actions');
const home=app.slice(app.indexOf('async function home()'),app.indexOf('async function recent()'));
assert.match(home,/Promise\.all\(\[storage\.listRecentNetworks\(\),storage\.listSavedNetworks\(\)\]\)/,'home counts come from the live IndexedDB-backed lists');
assert.match(home,/data-network-tab="recent" data-go="recent"[\s\S]*data-network-tab="saved" data-go="recent"/,'home cards carry explicit destinations for both network tabs');
assert.match(app,/if\(goButton\.dataset\.networkTab\)\{networkTab=goButton\.dataset\.networkTab;route='recent';/,'home action click forces Redes with its selected tab');
const clickHandler=app.slice(app.indexOf("root.addEventListener('click'"),app.indexOf("document.querySelector('.bottom-nav')"));assert.ok(clickHandler.indexOf("const goButton=e.target.closest('[data-go]')")<clickHandler.indexOf("const tab=e.target.closest('[data-network-tab]')"),'home cards with both attributes resolve navigation before the tab-only handler');assert.match(clickHandler,/if\(tab\)\{networkTab=tab\.dataset\.networkTab;route='recent';render\(\);return;\}/,'network tab controls also ensure the Redes route is active');
assert.match(app,/if\(open\)\{detailReturnRoute='recent'/,'opening a network from the list records a return destination');
assert.match(app,/if\(action==='detected-home'\)\{route=detailReturnRoute==='recent'\?'recent':'home'/,'back from network detail returns to its originating list');
assert.match(app,/data-action="validation-scan-clear"/);assert.match(app,/sessionStorage\.removeItem\('wifi-connect-scan-diagnostics'\)/,'validation can clear session-only scan diagnostics');
const safeSnapshots=[];const sensitiveSsid='Private SSID 932',sensitivePassword='PrivatePassword932';
const mockParsed={ssid:{value:sensitiveSsid},ssidCandidates:[{value:sensitiveSsid,corrected:true,correctionType:'wifi-band-context'}],password:{value:sensitivePassword,source:'ocr'},passwordCandidates:[{value:sensitivePassword}],security:{value:'WPA/WPA2'}};
const diagnosticRun=await analyzeRouterImage(new Blob(['fixture'],{type:'image/jpeg'}),{decodeQr:async()=>({status:'unavailable'}),recognize:async()=>({rawText:`SSID:${sensitiveSsid}\nPassword:${sensitivePassword}`,normalizedText:'redacted in diagnostics',confidence:88,durationMs:8,passes:[{id:'color',rawText:'',normalizedText:'',confidence:88,durationMs:8},{id:'grayscale-contrast',rawText:'',normalizedText:'',confidence:80,durationMs:9}]}),parse:()=>mockParsed,onDiagnostics:value=>safeSnapshots.push(value)});
assert.equal(diagnosticRun.diagnostics.bandReconstructionApplied,true);assert.equal(diagnosticRun.diagnostics.ocrPasses.length,2);assert.equal(diagnosticRun.diagnostics.fusion.ssidCandidateCount,1);assert.equal(diagnosticRun.diagnostics.durationMs>=0,true);
const safeDiagnosticJson=JSON.stringify(safeSnapshots.at(-1));assert.equal(safeDiagnosticJson.includes(sensitiveSsid),false);assert.equal(safeDiagnosticJson.includes(sensitivePassword),false);assert.equal(safeDiagnosticJson.includes('rawText'),false,'shared scan diagnostics never contain raw OCR or credentials');
console.log('scan UX: Orange direct-ready, Huawei band choice then ready, isolated review, simple error, recent-before-ready passed');
