import {isValidationAccessAllowed} from './config.js';
export const APP_VERSION='V1';
export const VALIDATION_SECTIONS=[
 {id:'safari',title:'Safari',tests:['Abrir aplicación en Safari','Navegación Inicio / Recientes / Ajustes','Generar QR manual','Guardar red','Añadir nota','Editar nota','Cerrar Safari y volver a abrir','Persistencia IndexedDB']},
 {id:'camera',title:'Cámara',tests:['Solicitar permiso','Cámara trasera','Preview correcta','Capturar fotografía','Repetir fotografía','Confirmar fotografía','Abandonar pantalla detiene cámara']},
 {id:'photos',title:'Fotos',tests:['Seleccionar foto desde galería','Foto vertical','Foto horizontal','Orientación correcta']},
 {id:'ocr',title:'OCR',tests:['Iniciar OCR','Mostrar progreso','Cancelar OCR','Repetir OCR','Obtener texto real','Revisar resultado']},
 {id:'parser',title:'Parser',tests:['Detectar SSID','Detectar contraseña','Detectar seguridad','Mostrar varios candidatos si existen','Corrección manual']},
 {id:'qr-final',title:'QR final',tests:['Generar QR tras revisión','Visualizar QR correctamente','Compartir QR','Escanear QR con otro teléfono','Conexión real a Wi-Fi']},
 {id:'pwa',title:'PWA instalada',tests:['Añadir a pantalla de inicio','Abrir en modo standalone','Navegación correcta','Cámara desde PWA','OCR desde PWA','IndexedDB persistente']},
 {id:'offline',title:'Offline',tests:['Abrir PWA sin Internet','Navegación offline','Generar QR offline','Abrir redes recientes offline','OCR offline después de haber descargado recursos']},
];
export const VALIDATION_FAILURE_CATEGORIES=['Cámara','Fotos','OCR','Parser','QR','PWA','Offline','Interfaz','Otro'];
export const VALIDATION_STATUS={untested:{label:'⚪ Sin probar',emoji:'⚪'},ok:{label:'🟢 OK',emoji:'🟢'},partial:{label:'🟡 Parcial',emoji:'🟡'},fail:{label:'🔴 Falla',emoji:'🔴'}};
export const VALIDATION_STORAGE_KEY='wifi-connect-physical-validation-v1';
export const isValidationMode=(locationLike,allowedHosts,validationPaths)=>isValidationAccessAllowed(locationLike,allowedHosts,validationPaths);
export function createChecklist(){return Object.fromEntries(VALIDATION_SECTIONS.flatMap(section=>section.tests.map(name=>[`${section.id}:${name}`,{status:'untested',note:'',category:'',description:'',steps:'',expected:'',actual:''}])));}
export function loadChecklist(storage=globalThis.localStorage){try{const saved=JSON.parse(storage?.getItem(VALIDATION_STORAGE_KEY)||'{}');const base=createChecklist();for(const [id,item] of Object.entries(base)){const value=saved[id];if(value&&Object.hasOwn(VALIDATION_STATUS,value.status))base[id]={...item,...value};}return base;}catch{return createChecklist();}}
export function saveChecklist(checklist,storage=globalThis.localStorage){storage?.setItem(VALIDATION_STORAGE_KEY,JSON.stringify(checklist));}
export function updateChecklistEntry(checklist,id,patch){if(!Object.hasOwn(checklist,id))throw new Error(`Prueba desconocida: ${id}`);const next={...checklist,[id]:{...checklist[id],...patch}};if(!Object.hasOwn(VALIDATION_STATUS,next[id].status))throw new Error('Estado de validación no válido.');return next;}
export function detectStandalone({navigatorStandalone=false,displayModeStandalone=false}={}){return navigatorStandalone===true||displayModeStandalone===true;}
function classify(userAgent=''){const ua=userAgent.toLowerCase();const device=/iphone/.test(ua)?'iPhone':/ipad/.test(ua)?'iPad':/android/.test(ua)?'Android':/windows/.test(ua)?'Windows':/macintosh|mac os/.test(ua)?'Mac':'Dispositivo no identificado';let browser='Navegador no identificado';if(/crios/.test(ua))browser='Chrome iOS';else if(/fxios/.test(ua))browser='Firefox iOS';else if(/edgios/.test(ua))browser='Edge iOS';else if(/safari/.test(ua)&&!/chrome|crios|android/.test(ua))browser='Safari';else if(/chrome|chromium/.test(ua))browser='Chrome';return {device,browser};}
export function collectCapabilities({navigatorObject=globalThis.navigator,windowObject=globalThis.window,documentObject=globalThis.document,userAgent=navigatorObject?.userAgent||'',viewport={width:windowObject?.innerWidth??null,height:windowObject?.innerHeight??null},date=new Date()}={}){
 const standalone=detectStandalone({navigatorStandalone:navigatorObject?.standalone,displayModeStandalone:!!windowObject?.matchMedia?.('(display-mode: standalone)')?.matches});
 const {device,browser}=classify(userAgent);
 return {device,browser,mode:standalone?'PWA instalada':browser==='Safari'?'Safari':'Navegador',timestamp:date.toISOString(),appVersion:APP_VERSION,userAgent,viewport,standalone,capabilities:{getUserMedia:typeof navigatorObject?.mediaDevices?.getUserMedia==='function',indexedDB:!!windowObject?.indexedDB||!!globalThis.indexedDB,clipboard:!!navigatorObject?.clipboard,webShare:typeof navigatorObject?.share==='function',serviceWorker:!!navigatorObject?.serviceWorker}};
}
const escapeRegExp=value=>value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
export function redactValidationText(text='',secrets=[]){let result=String(text??'');for(const secret of [...new Set(secrets.filter(value=>typeof value==='string'&&value.length>=2))].sort((a,b)=>b.length-a.length))result=result.replace(new RegExp(escapeRegExp(secret),'gi'),'[DATO WIFI OMITIDO]');result=result.replace(/\b(?:ssid|wi[ -]?fi\s*(?:password|key)|wlan\s*(?:password|key)|password|contrase(?:n|ñ)a|clave(?:\s+wifi)?)\s*[:=]\s*[^\n,;]+/gi,'[DATO WIFI OMITIDO]').replace(/WIFI:T:[^\n]+/gi,'[QR WIFI OMITIDO]');return result;}
function safeEntries(checklist,secrets){return Object.entries(checklist).map(([id,item])=>[id,{status:VALIDATION_STATUS[item.status]?.label||VALIDATION_STATUS.untested.label,note:redactValidationText(item.note,secrets),failure:item.status==='fail'||item.status==='partial'?{category:item.category||'',description:redactValidationText(item.description,secrets),steps:redactValidationText(item.steps,secrets),expected:redactValidationText(item.expected,secrets),actual:redactValidationText(item.actual,secrets)}:null}]);}
export function createValidationExport({checklist,environment=collectCapabilities(),secrets=[]}={}){return {version:1,device:environment.device,browser:environment.browser,mode:environment.mode,date:environment.timestamp,appVersion:APP_VERSION,environment:{userAgent:environment.userAgent,viewport:environment.viewport,standalone:environment.standalone,capabilities:environment.capabilities},checks:Object.fromEntries(safeEntries(checklist||createChecklist(),secrets))};}
export function createReadableReport({checklist,environment=collectCapabilities(),secrets=[]}={}){const lines=[`Netlixy ${APP_VERSION}`,`Dispositivo: ${environment.device}`,`Navegador: ${environment.browser}`,`Modo: ${environment.mode}`,`Fecha: ${environment.timestamp}`];for(const section of VALIDATION_SECTIONS){lines.push('',section.title);for(const name of section.tests){const item=checklist?.[`${section.id}:${name}`]||{status:'untested'};const status=VALIDATION_STATUS[item.status]||VALIDATION_STATUS.untested;const note=item.note?` · ${redactValidationText(item.note,secrets)}`:'';lines.push(`${status.emoji} ${name}${note}`);if(item.status==='fail'||item.status==='partial'){if(item.category)lines.push(`  Categoría: ${redactValidationText(item.category,secrets)}`);for(const [label,key] of [['Descripción','description'],['Pasos','steps'],['Esperado','expected'],['Actual','actual']])if(item[key])lines.push(`  ${label}: ${redactValidationText(item[key],secrets)}`);}}}return lines.join('\n');}
